#!/usr/bin/env node
var argv = process.argv.slice(2)
if(argv.indexOf("--help") != -1) {
  console.log([
    "Usage; ",
    " testfairy --platform=<android_or_ios> --api_key=<api_key> --apk_file=<relative_path_to_apk_file>",
    " [--icon-watermark=on_or_off]",
    " [--video=on_or_off]",
    " [--max_duration=time_duration_m]",
    " [--comment=comment]",
    " [--verbose]"
    ].join("\n"))
  process.exit(0)
}
var logger = require('semafor')();
var params = require('minimist')(argv)
var TestFairyUploader = require('./dest/TestFairyUploader.js'),
uploader = new TestFairyUploader(params)
var response = uploader.run();
var err = response[0];
if(err != null) return logger.fail(err.message);
logger.ok("File successfully uploaded to TestFairy");
console.log(response[1]);
